title: anti-symposium
email: your-email@example.com
description:
author:

# Social Profiles
twitter_username:
github_username:
facebook_username:

# Intro Section
intro_event_name: anti-symposium 2020
intro_event_details: July 22 - 26 in San Francisco, CA
intro_event_button_1: LEARN MORE
intro_event_button_2: REGISTER
